---
title: "GMBA SWE anomalies 2024"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    theme: 
      version: 5
      bootswatch: yeti
    navbar:
      - {title: "Home", href: "index.html", align: "left"}
      - {title: "2024", href: "2024.html", align: "left"}
      - {title: "2025", href: "2025.html", align: "left"}
      - {icon: "fa-github", title: "Source Code", href: "https://github.com/jb-smsc/gmba-swe", align: "right"}
editor_options: 
  chunk_output_type: console
---




```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(stringr)
library(sf)
library(leaflet)
library(htmltools)
# library(rmapshaper)
```


```{r data-prep-era5l, include=FALSE}
# moved to separate file

sf_plot <- readRDS("data/sf_plot_2024.rds")

# pal <- colorNumeric("RdYlBu", domain = sf_plot$xx_col, reverse = F)
# pal2 <- colorNumeric("RdYlBu", domain = sf_plot$xx_col, reverse = T)

pal_pos <- colorRampPalette(colors = c("#ffffbf", "#2c7bb6"), space = "Lab")(150)
pal_neg <- colorRampPalette(colors = c("#d7191c", "#ffffbf"), space = "Lab")(100)

pal <- colorNumeric(palette = c(pal_neg, pal_pos), domain = c(-100, 150))
pal2 <- colorNumeric(palette = c(pal_neg, pal_pos), domain = c(-100, 150), reverse = T)

# previewColors(colorNumeric(palette = c(pal_neg, pal_pos), domain = NULL), values = -100:150)

```


```{r data-prep-stations, include=FALSE}

sf_snotel <- readr::read_csv("data-raw/1Apil2024_SNOTEL_anom.csv",
                             show_col_types = FALSE) %>% 
  st_as_sf(coords = c("lon", "lat"), crs = 4326)

sf_bcab <- readr::read_csv("data-raw/1Apil2024_BCAB_anom.csv",
                           show_col_types = FALSE) %>% 
  st_as_sf(coords = c("lon", "lat"), crs = 4326)

sf_stn <- bind_rows(sf_snotel, sf_bcab)

sf_plot_stn <- sf_stn %>% 
  filter(nyrs > 20) %>% 
  mutate(xx_col = if_else(anom_pct > 150, 150, anom_pct) %>% as.integer) %>% 
  mutate(Name = str_to_title(station_name)) %>% 
  rename(peak_SWE_2024_anomaly = anom_pct,
         peak_SWE_2024 = snw,
         peak_SWE_clim_1992_2020 = clm) %>% 
  mutate(labels = str_c(
    "<table>",
    "<tr><th style='text-align: left'>", Name, "</th></tr>",
    "<tr>", 
    "<td>", "01 April SWE 2024 anomaly:", "</td>",
    "<td style='text-align: right; padding-left: 15px;'>", sprintf("%i %%", peak_SWE_2024_anomaly), "</td>",
    "</tr>",
    "<tr>", 
    "<td>", "01 April SWE 2024:", "</td>",
    "<td style='text-align: right; padding-left: 15px;'>", sprintf("%0.1f mm", peak_SWE_2024), "</td>",
    "</tr>",
    "<tr>", 
    "<td>", "01 April SWE average 1991-2020:", "</td>",
    "<td style='text-align: right; padding-left: 15px;'>", sprintf("%0.1f mm", peak_SWE_clim_1992_2020), "</td>",
    "</tr>",
    "</table>"
  )) 

```



## Column

### Map

```{r map, echo=FALSE}
leaflet(sf_plot) %>%
  addProviderTiles("CartoDB.Positron", group = "CartoDB") %>% 
  addProviderTiles("Esri.WorldTopoMap", group = "Topomap") %>% 
  addProviderTiles("Esri.WorldImagery", group = "WorldImagery") %>% 
  addPolygons(
    data = sf_plot,
    fillColor = ~pal(xx_col),
    fillOpacity = 1,
    color = ~pal(xx_col),
    opacity = 1,
    # stroke = FALSE,
    weight = 0,
    group = "ERA5-Land",
    highlightOptions = highlightOptions(
      color = "black",
      weight = 2,
      # dashArray = ""
      bringToFront = FALSE
    ),
    label = lapply(sf_plot$labels, htmltools::HTML),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "12px",
      offset = c(20, 20),
      direction = "auto")
  ) %>%
  addCircleMarkers(
    data = sf_plot_stn,
    stroke = TRUE,
    weight = 1,
    color = grey(0.3),
    opacity = 1,
    fillOpacity = 1,
    fillColor = ~pal(xx_col),
    radius = 5,
    group = "In-situ",
    label = lapply(sf_plot_stn$labels, htmltools::HTML),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "12px",
      offset = c(20, 20),
      direction = "auto")
  ) %>% 
  addLayersControl(
    baseGroups = c("CartoDB", "Topomap", "WorldImagery"),
    overlayGroups = c("ERA5-Land", "In-situ"),
    position = "topright"
  ) %>% 
  hideGroup("In-situ") %>%
  addLegend(pal = pal2, values = c(-100, 150), opacity = 1, 
            title = "01 April SWE</br>2024 anomaly",
            position = "bottomright",
            labFormat = labelFormat(transform = \(x) sort(x, decreasing = TRUE),
                                    suffix = " %"))
  
```
