---
title: "GMBA SWE anomalies 2025"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    theme: 
      version: 5
      bootswatch: yeti
    navbar:
      - {title: "Home", href: "index.html", align: "left"}
      - {title: "2024", href: "2024.html", align: "left"}
      - {title: "2025", href: "2025.html", align: "left"}
      - {icon: "fa-github", title: "Source Code", href: "https://github.com/jb-smsc/gmba-swe", align: "right"}
editor_options: 
  chunk_output_type: console
---





```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(stringr)
library(sf)
library(leaflet)
library(htmltools)
# library(rmapshaper)
```




```{r data-prep-era5l, echo=F}
# moved to separate file

sf_plot <- readRDS("data/sf_plot_2025.rds")

# pal <- colorNumeric("RdYlBu", domain = sf_plot$xx_col, reverse = F)
# pal2 <- colorNumeric("RdYlBu", domain = sf_plot$xx_col, reverse = T)

pal_pos <- colorRampPalette(colors = c("#ffffbf", "#2c7bb6"), space = "Lab")(150)
pal_neg <- colorRampPalette(colors = c("#d7191c", "#ffffbf"), space = "Lab")(100)

pal <- colorNumeric(palette = c(pal_neg, pal_pos), domain = c(-100, 150))
pal2 <- colorNumeric(palette = c(pal_neg, pal_pos), domain = c(-100, 150), reverse = T)

# previewColors(colorNumeric(palette = c(pal_neg, pal_pos), domain = NULL), values = -100:150)

```



```{r map, echo=F, out.width="100%"}
leaflet(sf_plot) %>%
  addProviderTiles("CartoDB.Positron", group = "CartoDB") %>% 
  addProviderTiles("Esri.WorldTopoMap", group = "Topomap") %>% 
  addProviderTiles("Esri.WorldImagery", group = "WorldImagery") %>% 
  addPolygons(
    data = sf_plot,
    fillColor = ~pal(xx_col),
    fillOpacity = 1,
    color = ~pal(xx_col),
    opacity = 1,
    # stroke = FALSE,
    weight = 0,
    group = "ERA5-Land",
    highlightOptions = highlightOptions(
      color = "black",
      weight = 2,
      # dashArray = ""
      bringToFront = FALSE
    ),
    label = lapply(sf_plot$labels, htmltools::HTML),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "12px",
      offset = c(20, 20),
      direction = "auto")
  ) %>%
  addLayersControl(
    baseGroups = c("CartoDB", "Topomap", "WorldImagery"),
    overlayGroups = c("ERA5-Land"),
    position = "topright"
  ) %>% 
  addLegend(pal = pal2, values = c(-100, 150), opacity = 1, 
            title = "01 April SWE</br>2025 anomaly",
            position = "bottomright",
            labFormat = labelFormat(transform = \(x) sort(x, decreasing = TRUE),
                                    suffix = " %"))
  
```
