---
title: "GMBA SWE anomalies"
output:
  html_document:
    theme:
      bslib: true
      version: 5
      bootswatch: yeti
---

<a href="2025.html" class="btn btn-primary" role="button">&rarr; 2025 anomalies</a>


<a href="2024.html" class="btn btn-primary" role="button">&rarr; 2024 anomalies</a>



# About

This is a contribution to the IACS joint body on mountain snow cover, working group 2.

Peak snow water equivalent (SWE) extracted from ERA5-Land for the GMBA mountain inventory v2.0. Peak SWE is taken as for Apr 1. Maps show anomalies relative to the climatology 1991-2020.

GBMA polygons have been simplified by a factor of 5 for simpler and faster online accessibility.

ERA5-Land processing by S. Gascoin ([sgascoin](https://github.com/sgascoin)), in-situ data by C. Mortimer ([mortc](https://github.com/mortc)), dashboard by M. Matiu ([mitmat](https://github.com/mitmat))




# Notes

Note that ERA5-Land has a simplistic snow scheme and coarse resolution for complex mountain terrain, but nonetheless shows good accuracy for large-scale SWE monitoring (see references).

Positive SWE anomalies capped to a maximum of 150%. 

SWE values (and consequently anomalies) for glaciated areas, such as in the Arctic, might not be reliable.

# Version history

v0.3 (2025-09-18)

- added 2025 anomalies
- minor restructuring

v0.2 (2024-06-14)

- added more references and notes in About page
- added in-situ anomalies to main map, layer turned off by default (only North America, see also [here](https://github.com/jb-smsc/snotel_anoms))

v0.1 (2024-05-29)

- first online version


# References 

Snethlage, M.A., Geschke, J., Spehn, E.M., Ranipeta, A., Yoccoz, N.G., Körner, Ch., Jetz, W., Fischer, M. & Urbach, D. A hierarchical inventory of the world’s mountains for global comparative mountain science. Nature Scientific Data. https://doi.org/10.1038/s41597-022-01256-y (2022).
Dataset

Snethlage, M.A., Geschke, J., Spehn, E.M., Ranipeta, A., Yoccoz, N.G., Körner, Ch., Jetz, W., Fischer, M. & Urbach, D. GMBA Mountain Inventory v2. GMBA-EarthEnv. https://doi.org/10.48601/earthenv-t9k2-1407 (2022).

Muñoz Sabater, J. (2019): ERA5-Land hourly data from 1950 to present. Copernicus Climate Change Service (C3S) Climate Data Store (CDS). https://doi.org/10.24381/cds.e2161bac. Date Accessed 04-24-2024. 

Sourp, L., Gascoin, S., Jarlan, L., Pedinotti, V., Bormann, K. J., and Baba, M. W.: Evaluation of high resolution snowpack simulations from global datasets and comparison with Sentinel-1 snow depth retrievals in the Sierra Nevada, USA, EGUsphere [preprint], https://doi.org/10.5194/egusphere-2024-791, 2024. 

Mudryk, L., Mortimer, C., Derksen, C., Elias Chereque, A., and Kushner, P.: Benchmarking of SWE products based on outcomes of the SnowPEx+ Intercomparison Project, EGUsphere [preprint], https://doi.org/10.5194/egusphere-2023-3014, 2024. 

